import { Character } from "../types";

export const characters: Character[] = [
  {
    id: "onOff",
    name: "On/Off",
    symbol: "ON/OFF",
    type: "action",
    color: "#A55C5C",
  },
  {
    id: "clearEntry",
    name: "Clear Entry",
    symbol: "CE",
    type: "action",
  },
  {
    id: "clearAll",
    name: "Clear All",
    symbol: "C",
    type: "action",
  },
  {
    id: "percentage",
    name: "Percentage",
    symbol: "%",
    type: "operator",
  },
  {
    id: "fraction",
    name: "Fraction",
    symbol: "1/x",
    type: "operator",
  },
  {
    id: "square",
    name: "Square",
    symbol: "x^2",
    display: "x²",
    type: "operator",
  },
  {
    id: "squareRoot",
    name: "SquareRoot",
    symbol: "√",
    type: "operator",
  },
  {
    id: "division",
    name: "Division",
    symbol: "/",
    type: "operator",
  },
  {
    id: "seven",
    name: "Seven",
    symbol: "7",
    type: "number",
  },
  {
    id: "eight",
    name: "Eight",
    symbol: "8",
    type: "number",
  },
  {
    id: "nine",
    name: "Nine",
    symbol: "9",
    type: "number",
  },
  {
    id: "multiply",
    name: "Multiply",
    symbol: "*",
    type: "operator",
  },
  {
    id: "four",
    name: "Four",
    symbol: "4",
    type: "number",
  },
  {
    id: "five",
    name: "Five",
    symbol: "5",
    type: "number",
  },
  {
    id: "six",
    name: "Six",
    symbol: "6",
    type: "number",
  },
  {
    id: "subtract",
    name: "Subtract",
    symbol: "-",
    type: "operator",
  },
  {
    id: "one",
    name: "One",
    symbol: "1",
    type: "number",
  },
  {
    id: "two",
    name: "Two",
    symbol: "2",
    type: "number",
  },
  {
    id: "three",
    name: "Three",
    symbol: "3",
    type: "number",
  },
  {
    id: "sum",
    name: "Sum",
    symbol: "+",
    type: "operator",
  },
  {
    id: "sign",
    name: "Sign",
    symbol: "+/-",
    type: "operator",
  },
  {
    id: "zero",
    name: "Zero",
    symbol: "0",
    type: "number",
  },
  {
    id: "decimal",
    name: "Decimal",
    symbol: ".",
    type: "number",
  },
  {
    id: "equals",
    name: "Equals",
    symbol: "=",
    type: "action",
  },
];
